apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-eventhub
  labels:
    app: sample-eventhub
spec:
  selector:
    matchLabels:
      app: sample-eventhub
  template:
    metadata:
      labels:
        app: sample-eventhub
    spec:
      containers:
      - name: sample-eventhub
        image: kedademoacr.azurecr.io/sample-eventhub:latest
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: EventHubTrigger
        envFrom:
        - secretRef:
            name: sample-eventhub
        readinessProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
        startupProbe:
          failureThreshold: 3
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 240
          httpGet:
            path: /
            port: 80
            scheme: HTTP
